export const FETCH_PRODUCTS='FETCH_PRODUCTS';
export const NEW_POST='NEW_POST';
export const LOGIN_CUST_AUTH='LOGIN_AUTH';
export const RESET_STORE='RESET_STORE';
export const CUSTOMER_CART='CUSTOMER_CART';
export const ADD_PRODUCT_TO_CART='ADD_PRODUCT_TO_CART';
export const LOGIN_ADMIN_AUTH='LOGIN_ADMIN_AUTH';
export const ADD_PRODUCT='ADD_PRODUCT';